---
title: "Melissa - Synthetic data analysis"
author:
- name: Andreas C. Kapourani
  affiliation: School of Informatics, University of Edinburgh, UK
  email: c.a.kapourani or kapouranis.andreas@gmail.com
- name: Guido Sanguinetti
  affiliation: School of Informatics, University of Edinburgh, UK
  email: G.Sanguinetti@ed.ac.uk
output:
  BiocStyle::html_document:
    toc_float: true
---

```{r echo=FALSE, include=FALSE}
suppressPackageStartupMessages(library(BPRMeth))
suppressPackageStartupMessages(library(purrr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(cowplot))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(ROCR))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(RColorBrewer))
```

```{r echo=FALSE, include=FALSE}
# Define ggplot2 theme for line plots
line_theme <- function(){
  p <- theme(
      plot.title = element_text(size = 28, face = 'bold', 
                                margin = margin(0,0,0,0), hjust = 0.5),
      axis.text = element_text(size = rel(1.35), color = 'black'),
      axis.title = element_text(size = rel(1.95), color = 'black'),
      axis.title.y = element_text(margin = margin(0,15,0,0)),
      axis.title.x = element_text(margin = margin(15,0,0,0)),
      axis.ticks.x = element_line(colour = "black", size = rel(0.8)),
      axis.ticks.y = element_blank(),
      legend.position = "right",
      legend.key.size = unit(2.2, 'lines'),
      legend.title = element_text(size = 26, face = 'bold'),
      legend.text = element_text(size = 22),
      panel.border = element_blank(),
      panel.grid.major = element_line(colour = "gainsboro"),
      panel.background = element_blank()
    )
  return(p)
}

# Create AUC errorbar plot
errorbars_plot <- function(dt, title = "", x_lab = "", y_lab = ""){
  pd <- position_dodge(0.1) # move them .1 to the left and right
  p <- ggplot(dt, aes(x = x, y = y, colour = Model, group = Model)) + 
    geom_errorbar(aes(ymin = y - sd_y, ymax = y + sd_y), 
                  colour = "black", width = .3, position = pd) +
    geom_line(position = pd, size = 1.5) +
    geom_point(position = pd, size = 3, shape = 21, fill = "white") +
    scale_color_manual(values = c("red3", "cornflowerblue", "chocolate2", "green4", "dodgerblue4")) + 
    #scale_y_continuous(limits = c(0.78, .96), breaks=pretty_breaks(n=6)) + 
    labs(title = title, x = x_lab, y = y_lab) + line_theme() 
  return(p)
}

# Create AUC jitter plot
auc_jitter_plot <- function(dt, title = "", x_lab = "", y_lab = ""){
  # pd <- position_dodge(0.1) # move them .1 to the left and right
  p <- ggplot(dt, aes(x = x, y = y, colour = Model, group = Model)) + 
    geom_jitter(size = 2.1, width = 0.15, height = -0.1, shape = 21) +
    # geom_point(data = dt2, aes(x = x, y = y), position = pd, size = 3, shape = 21, fill = "white") +
    geom_smooth(aes(fill = Model), span = 0.15, method = "loess", 
                se = TRUE, size = 1.3, alpha = 0.1) +
    scale_color_manual(values = c("red3", "cornflowerblue", "chocolate2", "green4", "dodgerblue4")) + 
    scale_fill_manual(values = c("red3", "cornflowerblue", "chocolate2", "green4", "dodgerblue4")) + 
    labs(title = title, x = x_lab, y = y_lab) + line_theme() 
  return(p)
}

# Create ARI jitter plot
ari_jitter_plot <- function(dt, title = "", x_lab = "", y_lab = ""){
  # pd <- position_dodge(0.1) # move them .1 to the left and right
  p <- ggplot(dt, aes(x = x, y = y, colour = Model, group = Model)) + 
    geom_jitter(size = 2.1, width = 0.15, height = -0.1, shape = 21) +
    # geom_point(data = dt2, aes(x = x, y = y), position = pd, size = 3, shape = 21, fill = "white") +
    geom_smooth(aes(fill = Model), span = 0.15, method = "loess", 
                se = FALSE, size = 1.3, alpha = 0.1) +
    scale_color_manual(values = c("red3", "dodgerblue4", "chocolate2", "green4", "cornflowerblue")) + 
    scale_fill_manual(values = c("red3", "dodgerblue4", "chocolate2", "green4", "cornflowerblue")) + 
    labs(title = title, x = x_lab, y = y_lab) + line_theme() 
  return(p)
}


# Create AUC jitter plot
eff_jitter_plot <- function(dt, title = "", x_lab = "", y_lab = ""){
  # pd <- position_dodge(0.1) # move them .1 to the left and right
  p <- ggplot(dt, aes(x = x, y = y, colour = Model, group = Model)) + 
    geom_jitter(size = 2.1, width = 0.2, height = .3, shape = 21) +
    # geom_point(data = dt2, aes(x = x, y = y), position = pd, size = 3, shape = 21, fill = "white") +
    geom_smooth(aes(fill = Model), method = "loess", 
                se = FALSE, size = 1.3, alpha = 0.1) +
    scale_color_manual(values = c("red3", "dodgerblue4", "chocolate2", "green4", "cornflowerblue")) + 
    scale_fill_manual(values = c("red3", "dodgerblue4", "chocolate2", "green4", "cornflowerblue")) + 
    labs(title = title, x = x_lab, y = y_lab) + line_theme() 
  return(p)
}
```

<!-- # Parse and filter data -->
```{r initial_params, echo=FALSE, include=FALSE}
# Data
io <- list()
io$script_dir <- "../"
io$data_dir   <- "../local-data/melissa/synthetic/imputation/"
io$cpg_dir    <- paste0(io$data_dir, "coverage/")
io$var_dir    <- paste0(io$data_dir, "dissimilarity/")
io$K          <- 4
io$basis      <- 4
io$cpg_prcg   <- 0.4
io$cl_var     <- 0.5
io$data_prcg  <- 0.1
io$reg_prcg   <- 1
R.utils::sourceDirectory(paste0(io$script_dir, "lib/"), modifiedOnly = FALSE)
```


<!-- # Parse and filter data -->
```{r load_cpg_data, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
# Different CpG coverages
io$cpg_analysis <- seq(0.1, 0.9, 0.1)
# Load synthetic data
cpg_data <- readRDS(paste0(io$cpg_dir, "raw/encode_data.rds")) 
# Load joint analysis results
joint_cpg_prcg <- readRDS(paste0(io$cpg_dir, "encode_joint_K", io$K, "_rbf", io$basis, 
                                "_dataTrain", io$data_prcg, 
                                "_regionTrain", io$reg_prcg, 
                                "_clusterVar", io$cl_var, ".rds"))
# Load independent analysis results
indep_cpg_prcg <- readRDS(paste0(io$cpg_dir, "encode_indep_K", io$K, "_rbf", io$basis, 
                                "_dataTrain", io$data_prcg, 
                                "_regionTrain", io$reg_prcg, 
                                "_clusterVar", io$cl_var, ".rds"))

# Load RF analysis results
rf_cpg_prcg <- readRDS(paste0(io$cpg_dir, "encode_rf_indep_K", io$K, "_rbf", io$basis, 
                                "_dataTrain", io$data_prcg, 
                                "_regionTrain", io$reg_prcg, 
                                "_clusterVar", io$cl_var, ".rds"))

N <- length(joint_cpg_prcg)    # Numer of replications
M <- length(io$cpg_analysis)  # Number of Cpg coverage thresholds

dt_cpg_analysis <- data.table(cpg_cov = numeric(), auc_melissa = numeric(), 
                              auc_melissa_rate = numeric(), auc_indep_prof = numeric(), 
                              auc_indep_rate = numeric(), auc_rf = numeric(),
                              melissa_ari = numeric(), melissa_rate_ari = numeric(),
                              melissa_error = numeric(), melissa_rate_error = numeric())
# Iterate over each replication of the experiment
for (i in 1:length(joint_cpg_prcg)) {     # Itrate over simulations
  for (m in 1:length(io$cpg_analysis)) {  # Iterate over CpG percentages
    dt <- data.table(cpg_cov = io$cpg_analysis[m], 
                     auc_melissa = performance(prediction(joint_cpg_prcg[[i]]$eval_perf[[m]]$eval_prof$pred_obs, 
                               joint_cpg_prcg[[i]]$eval_perf[[m]]$eval_prof$act_obs), "auc")@y.values[[1]],
                     auc_melissa_rate = performance(prediction(joint_cpg_prcg[[i]]$eval_perf[[m]]$eval_mean$pred_obs, 
                               joint_cpg_prcg[[i]]$eval_perf[[m]]$eval_mean$act_obs), "auc")@y.values[[1]],
                     auc_indep_prof = performance(prediction(indep_cpg_prcg[[i]]$eval_perf[[m]]$eval_prof$pred_obs, 
                               indep_cpg_prcg[[i]]$eval_perf[[m]]$eval_prof$act_obs), "auc")@y.values[[1]],
                     auc_indep_rate = performance(prediction(indep_cpg_prcg[[i]]$eval_perf[[m]]$eval_mean$pred_obs, 
                               indep_cpg_prcg[[i]]$eval_perf[[m]]$eval_mean$act_obs), "auc")@y.values[[1]],
                     auc_rf = performance(prediction(rf_cpg_prcg[[i]]$eval_perf[[m]]$pred_obs, 
                               rf_cpg_prcg[[i]]$eval_perf[[m]]$act_obs), "auc")@y.values[[1]],
                     melissa_ari = cluster_ari(cpg_data$synth_data[[i]]$C_true, joint_cpg_prcg[[i]]$melissa_prof[[m]]$r_nk),
                     melissa_rate_ari = cluster_ari(cpg_data$synth_data[[i]]$C_true, joint_cpg_prcg[[i]]$melissa_rate[[m]]$r_nk),
                     melissa_error = cluster_error(cpg_data$synth_data[[i]]$C_true, joint_cpg_prcg[[i]]$melissa_prof[[m]]$r_nk),
                     melissa_rate_error = cluster_error(cpg_data$synth_data[[i]]$C_true, joint_cpg_prcg[[i]]$melissa_rate[[m]]$r_nk))
    # Add results to final data.table
    dt_cpg_analysis <- rbind(dt_cpg_analysis, dt)
  }
}
rm(iter, dt, i, m, N, M, joint_cpg_prcg, indep_cpg_prcg, cpg_data)
```

# AUC performance across CpG coverage 
```{r auc_plot_cpg, fig.wide=TRUE, echo=FALSE, include=TRUE, warning=FALSE, fig.width=12, fig.height=8}
dt_cpg_jitter <- copy(dt_cpg_analysis)
dt_cpg_jitter <- dt_cpg_jitter[, c("melissa_ari", "melissa_rate_ari", "melissa_error", "melissa_rate_error") := list(NULL, NULL)] %>% setnames(c("cpg_cov", "auc_melissa", "auc_melissa_rate", "auc_indep_prof", "auc_indep_rate", "auc_rf"), c("x", "Melissa", "Melissa Rate", "Indep Profile", "Indep Rate", "RF")) %>% .[, x := as.factor(x)] %>% melt(variable.name = "Model", value.name = "y") 
p_auc_cpg_jitter <- auc_jitter_plot(dt_cpg_jitter, x_lab = "CpG coverage", y_lab = "AUC", title = "")
print(p_auc_cpg_jitter)
```

<!-- # Parse and filter data -->
```{r load_diss_data, echo=FALSE, include=FALSE, warning=FALSE, message=FALSE}
# Different CpG coverages
io$cluster_var_analysis <- seq(0, 1, .1)
# Load joint analysis results
joint_cl_var <- readRDS(paste0(io$var_dir, "encode_joint_K", io$K, "_rbf", io$basis, 
                                "_dataTrain", io$data_prcg, 
                                "_regionTrain", io$reg_prcg, 
                                "_cpgTrain", io$cpg_prcg, ".rds"))
# Load independent analysis results
indep_cl_var <- readRDS(paste0(io$var_dir, "encode_indep_K", io$K, "_rbf", io$basis, 
                                "_dataTrain", io$data_prcg, 
                                "_regionTrain", io$reg_prcg, 
                                "_cpgTrain", io$cpg_prcg, ".rds"))
# Load RF analysis results
rf_cl_var <- readRDS(paste0(io$var_dir, "encode_rf_indep_K", io$K, "_rbf", io$basis, 
                                "_dataTrain", io$data_prcg, 
                                "_regionTrain", io$reg_prcg, 
                                "_cpgTrain", io$cpg_prcg, ".rds"))

N <- length(joint_cl_var)             # Numer of replications
M <- length(io$cluster_var_analysis)  # Number of cell variability thresholds
dt_var_analysis <- data.table(cell_var = numeric(), auc_melissa = numeric(), 
                              auc_melissa_rate = numeric(), auc_indep_prof = numeric(), 
                              auc_indep_rate = numeric(), auc_rf = numeric(),
                                      melissa_ari = numeric(), melissa_rate_ari = numeric(),
                                      melissa_error = numeric(), melissa_rate_error = numeric())
# Iterate over each replication of the experiment
for (i in 1:length(joint_cl_var)) {
  for (m in 1:length(io$cluster_var_analysis)) {
    # Load synthetic data
    var_data <- readRDS(paste0(io$var_dir, "raw/data-sims/encode_data_", io$cluster_var_analysis[m], "_", i, ".rds")) 
    dt <- data.table(cell_var = io$cluster_var_analysis[m], 
                     auc_melissa = performance(prediction(joint_cl_var[[i]]$eval_perf[[m]]$eval_prof$pred_obs, 
                               joint_cl_var[[i]]$eval_perf[[m]]$eval_prof$act_obs), "auc")@y.values[[1]],
                     auc_melissa_rate = performance(prediction(joint_cl_var[[i]]$eval_perf[[m]]$eval_mean$pred_obs, 
                               joint_cl_var[[i]]$eval_perf[[m]]$eval_mean$act_obs), "auc")@y.values[[1]],
                     auc_indep_prof = performance(prediction(indep_cl_var[[i]]$eval_perf[[m]]$eval_prof$pred_obs, 
                               indep_cl_var[[i]]$eval_perf[[m]]$eval_prof$act_obs), "auc")@y.values[[1]],
                     auc_indep_rate = performance(prediction(indep_cl_var[[i]]$eval_perf[[m]]$eval_mean$pred_obs, 
                               indep_cl_var[[i]]$eval_perf[[m]]$eval_mean$act_obs), "auc")@y.values[[1]],
                     auc_rf = performance(prediction(rf_cl_var[[i]]$eval_perf[[m]]$pred_obs, 
                               rf_cl_var[[i]]$eval_perf[[m]]$act_obs), "auc")@y.values[[1]],
                     melissa_ari = cluster_ari(var_data$synth_data$C_true, joint_cl_var[[i]]$melissa_prof[[m]]$r_nk),
                     melissa_rate_ari = cluster_ari(var_data$synth_data$C_true, joint_cl_var[[i]]$melissa_rate[[m]]$r_nk),
                     melissa_error = cluster_error(var_data$synth_data$C_true, joint_cl_var[[i]]$melissa_prof[[m]]$r_nk),
                     melissa_rate_error = cluster_error(var_data$synth_data$C_true, joint_cl_var[[i]]$melissa_rate[[m]]$r_nk))
    # Add results to final data.table
    dt_var_analysis <- rbind(dt_var_analysis, dt)
  }
}
rm(iter, i, m, N, M, joint_cl_var, indep_cl_var, dt, var_data)
```


# AUC performance across cluster dissimilarity 
```{r auc_plot_diss, fig.wide=TRUE, echo=FALSE, include=TRUE, warning=FALSE, fig.width=12, fig.height=8}
dt_var_jitter <- copy(dt_var_analysis)
dt_var_jitter <- dt_var_jitter[, c("melissa_ari", "melissa_rate_ari", "melissa_error", "melissa_rate_error") := list(NULL, NULL)] %>% setnames(c("cell_var", "auc_melissa", "auc_melissa_rate", "auc_indep_prof", "auc_indep_rate", "auc_rf"), c("x", "Melissa", "Melissa Rate", "Indep Profile", "Indep Rate", "RF")) %>% .[, x := as.factor(x)] %>% melt(variable.name = "Model", value.name = "y") 
p_auc_var_jitter <- auc_jitter_plot(dt_var_jitter, x_lab = "Cluster dissimilarity", y_lab = "AUC", title = "")
print(p_auc_var_jitter)
```

# ARI performance CpG coverage
```{r ari_plot_cpg, fig.wide=TRUE, echo=FALSE, include=TRUE, warning=FALSE, fig.width=10, fig.height=7}
dt_ari_cpg_jitter <- copy(dt_cpg_analysis)
dt_ari_cpg_jitter <- dt_ari_cpg_jitter[, c("auc_melissa", "auc_melissa_rate", "auc_indep_prof", "auc_indep_rate", "auc_rf", "melissa_error", "melissa_rate_error") := list(NULL, NULL, NULL, NULL, NULL, NULL, NULL)] %>% setnames(c("cpg_cov", "melissa_ari", "melissa_rate_ari"), c("x", "Melissa", "Melissa Rate")) %>% .[, x := as.factor(x)] %>% melt(variable.name = "Model", value.name = "y")
p_ari_cpg_jitter <- ari_jitter_plot(dt_ari_cpg_jitter, x_lab = "CpG coverage", y_lab = "AUC", title = "")
print(p_ari_cpg_jitter)
```

# ARI performance cluster dissimilarity
```{r ari_plot_diss, fig.wide=TRUE, echo=FALSE, include=TRUE, warning=FALSE, fig.width=10, fig.height=7}
dt_ari_var_jitter <- copy(dt_var_analysis)
dt_ari_var_jitter <- dt_ari_var_jitter[, c("auc_melissa", "auc_melissa_rate", "auc_indep_prof", "auc_indep_rate", "auc_rf","melissa_error", "melissa_rate_error") := list(NULL, NULL, NULL, NULL, NULL, NULL, NULL)] %>% setnames(c("cell_var", "melissa_ari", "melissa_rate_ari"), c("x", "Melissa", "Melissa Rate")) %>% .[, x := as.factor(x)] %>% melt(variable.name = "Model", value.name = "y")
p_ari_var_jitter <- ari_jitter_plot(dt_ari_var_jitter, x_lab = "Cluster dissimilarity", y_lab = "ARI", title = "")
print(p_ari_var_jitter)
```


# Model selection
```{r model_selection, fig.wide=TRUE, echo=FALSE, include=TRUE, warning=FALSE, fig.width=10, fig.height=7}
# Data
io <- list()
io$script_dir    <- "../"
io$model_sel_dir <- "../local-data/melissa/synthetic/model-selection/"
io$K <- 10
# Different CpG coverages
io$cluster_var_analysis <- seq(0, 1, .1)
# Load joint analysis results
broad_model <- readRDS(paste0(io$model_sel_dir, "encode_broad_model_selection_K", io$K, ".rds"))
strict_model <- readRDS(paste0(io$model_sel_dir, "encode_strict_model_selection_K", io$K, ".rds"))

dt_model_analysis <- data.table(cell_var = numeric(), 
                              broad_K = numeric(), 
                              strict_K = numeric())
for (i in 1:5) {
  for (m in 1:length(io$cluster_var_analysis)) {
      dt <- data.table(cell_var = io$cluster_var_analysis[m], 
                       broad_K = length(which(broad_model[[i]]$melissa[[m]]$delta > 6)),
                       strict_K = length(which(strict_model[[i]]$melissa[[m]]$delta > 6)))
                        # Add results to final data.table
    dt_model_analysis <- rbind(dt_model_analysis, dt)
  }
}
rm(dt, i, m, broad_model, strict_model)

dt_model_jitter <- copy(dt_model_analysis)
dt_model_jitter <- dt_model_jitter %>% setnames(c("cell_var", "broad_K", "strict_K"), 
                                                c("x", "Broad Prior", "Strict Prior")) %>% 
    .[, x := as.factor(x)] %>% melt(variable.name = "Model", value.name = "y")
p_model_jitter <- ari_jitter_plot(dt_model_jitter, x_lab = "Cluster dissimilarity", 
                                  y_lab = "Clusters K", title = "")
print(p_model_jitter)
```


# Model efficicency
```{r model_efficiency, fig.wide=TRUE, warning=FALSE, echo=FALSE, include=TRUE, fig.width=10, fig.height=7}
# Data
library(microbenchmark)
io <- list()
io$script_dir    <- "../"
io$model_eff_dir <- "../local-data/melissa/synthetic/model-efficiency/"
io$K <- 3
io$M <- 200
io$N <- c(50, 100, 200, 500, 1000, 2000)

io$iter <- seq(1, 5)
dt_efficiency_analysis <- data.table(cells = numeric(), min_gibbs = numeric(), min_vb = numeric())
for (i in io$iter) {
    for (n in io$N) {
        eff_dt <- readRDS(paste0(io$model_eff_dir, "model_efficiency_K", io$K, "_M", 
                                 io$M, "_N", n, "_", i, ".rds"))[[1]]
        dt <- data.table(cells = n, min_gibbs = (eff_dt$time[which(eff_dt[, "expr"] == "gibbs")]) / 10^9 / 60 / 60,
                         min_vb = (eff_dt$time[which(eff_dt[, "expr"] == "vb")]) / 10^9 / 60 / 60 )
                        # Add results to final data.table
    dt_efficiency_analysis <- rbind(dt_efficiency_analysis, dt)
    }
}
rm(i, n, eff_dt)

dt_eff_jitter <- copy(dt_efficiency_analysis)
dt_eff_jitter <- dt_eff_jitter %>% setnames(c("cells", "min_gibbs", "min_vb"), c("x", "Gibbs", "VB")) %>% 
    .[, x := as.factor(x)] %>% melt(variable.name = "Model", value.name = "y") %>% 
    .[, Model := factor(Model, levels = c("VB", "Gibbs"))]
p_eff_jitter <- eff_jitter_plot(dt_eff_jitter, x_lab = "Cells", y_lab = "Hours", title = "")
print(p_eff_jitter)
```

# Joint plot AUC ENCODE synthetic
```{r joint_plot_auc, fig.wide=TRUE, eval=TRUE, echo=FALSE, include=TRUE, warning=FALSE, message=FALSE, fig.height=7, fig.width=16}
## AUC plot
p_auc_cpg_jitter <- auc_jitter_plot(dt_cpg_jitter, x_lab = "CpG coverage", y_lab = "AUC", title = "") +
    theme(legend.position = "none") + scale_y_continuous(limits = c(0.5, .9), breaks = pretty_breaks(n = 6))
p_auc_var_jitter <- auc_jitter_plot(dt_var_jitter, x_lab = "Cluster dissimilarity", y_lab = "AUC", title = "") +
    theme(legend.position = "right") + scale_y_continuous(limits = c(0.5, .9), breaks = pretty_breaks(n = 6))

final_fig_auc <- plot_grid(p_auc_cpg_jitter, p_auc_var_jitter, labels = c("a", "b"), 
                           label_size = 25, ncol = 2, nrow = 1, rel_widths = c(1, 1.3))
print(final_fig_auc)

# pdf(file=paste0("out/auc-encode.pdf"), width = 16, height = 5.5, useDingbats = FALSE)
# final_fig_auc
# dev.off()
```


# Joint plot performance ENCODE synthetic
```{r joint_plot_analysis, fig.wide=TRUE, eval=TRUE, echo=FALSE, include=TRUE, warning=FALSE, message=FALSE, fig.height=14, fig.width=16}
# Joint plot of ARI, model selection and model efficiency
p_ari_var_jitter <- ari_jitter_plot(dt_ari_var_jitter, x_lab = "Cluster dissimilarity", y_lab = "ARI", title = "Cluster performance") +
    theme(legend.position = c(0.55, 0.23)) + 
    scale_x_discrete(breaks = pretty_breaks(n = 6))
p_ari_cpg_jitter <- ari_jitter_plot(dt_ari_cpg_jitter, x_lab = "CpG coverage", y_lab = "ARI", title = "Cluster performance") +
    theme(legend.position = c(0.55, 0.23))  +
    scale_x_discrete(breaks = pretty_breaks(n = 5))
p_model_jitter <- ari_jitter_plot(dt_model_jitter, x_lab = "Cluster dissimilarity", y_lab = "Clusters K", title = "Model Selection") +
    theme(legend.position = c(0.65, 0.23)) +
    scale_x_discrete(breaks = pretty_breaks(n = 6))
p_eff_jitter <- eff_jitter_plot(dt_eff_jitter, x_lab = "Cells", y_lab = "Hours", title = "Model Efficiency") +
    theme(legend.position = c(0.06, 0.8))

top_ari_analysis <- plot_grid(p_ari_cpg_jitter, p_ari_var_jitter,  labels = c("a", "b"), 
                              label_size = 25, ncol = 2, nrow = 1, rel_widths = c(1, 1))
bot_perf_analysis <- plot_grid(p_model_jitter, p_eff_jitter,  labels = c("c", "d"), 
                               label_size = 25, ncol = 2, nrow = 1, rel_widths = c(1, 1))

final_encode_analysis <- plot_grid(top_ari_analysis, bot_perf_analysis, ncol = 1, nrow = 2, rel_widths = c(1, 1))
print(final_encode_analysis)

# pdf(file=paste0("out/encode-analysis.pdf"), width = 12, height = 10, useDingbats = FALSE)
# final_analysis
# dev.off() 
```

